import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { createToolDocument, getAttribution, getToolDocuments, getToolPdfUrl, getToolVisitorId, trackToolEvent } from "../services/api";
import "../styles/free-tools.css";

const money = (n) => `₹${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const today = () => new Date().toISOString().slice(0, 10);
const makeItem = () => ({ id: crypto.randomUUID(), description: "", quantity: 1, rate: 0 });
const formatDate = (v) => { if (!v) return "—"; const [y,m,d] = v.split("-"); return d&&m&&y ? `${d}/${m}/${y}` : v; };
function Field({label,required,...props}) { return <label className="invoice-field"><span>{label}{required ? " *" : ""}</span><input {...props}/></label>; }
function Section({number,title,children}) { return <section className="invoice-section"><h2><span>{number}.</span> {title}</h2>{children}</section>; }
function Preview({seller,buyer,receipt,items,totals}) { return <div className="invoice-paper quotation-paper receipt-paper">
  <header className="invoice-paper-header"><div className="invoice-brand"><div><h2>{seller.name || "Your Business"}</h2>{seller.gstin&&<p>GSTIN: {seller.gstin}</p>}{(seller.email||seller.phone)&&<p>{seller.email}{seller.email&&seller.phone?" | ":""}{seller.phone}</p>}{seller.address&&<p>{seller.address}</p>}</div></div><div className="invoice-title-block"><strong>PAYMENT RECEIPT</strong><span>{receipt.number||"REC-001"}</span></div></header>
  <div className="invoice-info-grid"><div className="invoice-party-box"><small>RECEIVED FROM</small><strong>{buyer.name||"Customer Name"}</strong>{buyer.gstin&&<span>GSTIN: {buyer.gstin}</span>}{(buyer.email||buyer.phone)&&<span>{buyer.email}{buyer.email&&buyer.phone?" | ":""}{buyer.phone}</span>}{buyer.address&&<span>{buyer.address}</span>}</div><div className="invoice-meta-box"><div><span>Receipt Date</span><b>{formatDate(receipt.date)}</b></div><div><span>Payment Method</span><b>{receipt.method}</b></div><div><span>Reference</span><b>{receipt.reference||"—"}</b></div></div></div>
  <div className="receipt-status">PAYMENT RECEIVED</div>
  <table className="invoice-items-table"><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>Rate (₹)</th><th>Amount (₹)</th></tr></thead><tbody>{items.filter(x=>x.description.trim()).map((x,i)=><tr key={x.id}><td>{i+1}</td><td>{x.description}</td><td>{Number(x.quantity)||0}</td><td>{Number(x.rate||0).toFixed(2)}</td><td>{money((Number(x.quantity)||0)*(Number(x.rate)||0)).replace("₹","")}</td></tr>)}</tbody></table>
  <div className="invoice-summary"><div><span>Subtotal</span><b>{money(totals.gross)}</b></div><div><span>Discount</span><b>- {money(totals.discount)}</b></div><div><span>Taxable Amount</span><b>{money(totals.taxable)}</b></div><div><span>GST ({receipt.gstRate}%)</span><b>{money(totals.tax)}</b></div><div className="invoice-grand-total"><span>AMOUNT RECEIVED</span><strong>{money(totals.total)}</strong></div></div>
  {receipt.notes&&<div className="quotation-note">{receipt.notes}</div>}<div className="invoice-thankyou">Thank you for your payment!</div>
</div>; }
export default function ReceiptTool(){
 const visitorId=getToolVisitorId();
 const [seller,setSeller]=useState({name:"Your Business",gstin:"",email:"",phone:"",address:""});
 const [buyer,setBuyer]=useState({name:"Customer Name",gstin:"",email:"",phone:"",address:""});
 const [receipt,setReceipt]=useState({number:"REC-001",date:today(),method:"UPI",reference:"",gstRate:"18",discount:"0",notes:"Payment received in full. Thank you for your business."});
 const [items,setItems]=useState([makeItem()]); const [saved,setSaved]=useState(null); const [history,setHistory]=useState([]); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{getToolDocuments(visitorId).then(d=>setHistory(d.filter(x=>x.document_type==="receipt"))).catch(()=>{});localStorage.setItem("fw_last_tool_slug","receipt-generator");const a=getAttribution();trackToolEvent({tool:"receipt-generator",event_type:"tool_start",visitor_id:visitorId,session_id:visitorId,...a}).catch(()=>{});},[visitorId,saved]);
 const totals=useMemo(()=>{const gross=items.reduce((s,x)=>s+Math.max(0,Number(x.quantity)||0)*Math.max(0,Number(x.rate)||0),0);const discount=Math.min(gross,Math.max(0,Number(receipt.discount)||0));const taxable=gross-discount;const tax=taxable*Math.max(0,Number(receipt.gstRate)||0)/100;return {gross,discount,taxable,tax,total:taxable+tax};},[items,receipt.discount,receipt.gstRate]);
 const update=(set,k,v)=>set(x=>({...x,[k]:v}));
 const reset=()=>{setSeller({name:"Your Business",gstin:"",email:"",phone:"",address:""});setBuyer({name:"Customer Name",gstin:"",email:"",phone:"",address:""});setReceipt({number:"REC-001",date:today(),method:"UPI",reference:"",gstRate:"18",discount:"0",notes:"Payment received in full. Thank you for your business."});setItems([makeItem()]);setSaved(null);setError("");};
 const save=async()=>{setError("");const valid=items.filter(x=>x.description.trim());if(!seller.name.trim()||!buyer.name.trim()||!receipt.number.trim()||!valid.length){setError("Please enter seller name, customer name, receipt number and at least one item.");return;}setSaving(true);try{const a=getAttribution();const doc=await createToolDocument({tool:"receipt-generator",document_type:"receipt",document_number:receipt.number.trim(),visitor_id:visitorId,business_details:seller,customer_details:buyer,line_items:valid.map(({id,...x})=>({...x,quantity:Number(x.quantity)||0,rate:Number(x.rate)||0,amount:(Number(x.quantity)||0)*(Number(x.rate)||0)})),tax_details:{gst_rate:Number(receipt.gstRate)||0,payment_method:receipt.method},totals,metadata:{receipt_date:receipt.date,payment_method:receipt.method,reference:receipt.reference,notes:receipt.notes,attribution:a,version:"receipt-v2"}});setSaved(doc);trackToolEvent({tool:"receipt-generator",event_type:"document_created",visitor_id:visitorId,session_id:visitorId,document:doc.id,...a}).catch(()=>{});}catch(e){setError(e.message||"Could not save receipt. Please make sure the backend is running.");}finally{setSaving(false);}};
 return <main className="invoice-tool-page"><div className="invoice-tool-container"><div className="invoice-toolbar"><Link to="/tools" className="invoice-back">← All Free Tools</Link><div className="invoice-toolbar-title"><span className="eyebrow-cyan">FREE TOOL</span><h1>Receipt Generator</h1><p>Create professional payment receipts and download as PDF</p></div><div className="invoice-toolbar-actions"><button className="invoice-clear" onClick={reset}>Clear All</button>{saved&&<a className="invoice-download" href={getToolPdfUrl(saved.id,visitorId)} onClick={()=>trackToolEvent({tool:"receipt-generator",event_type:"pdf_downloaded",visitor_id:visitorId,session_id:visitorId,document:saved.id}).catch(()=>{})}>Download PDF</a>}</div></div>
 <div className="invoice-workspace"><div className="invoice-form-panel"><Section number="1" title="Seller (Your Business) Details"><div className="invoice-grid two"><Field label="Business Name" required value={seller.name} onChange={e=>update(setSeller,"name",e.target.value)}/><Field label="GSTIN" value={seller.gstin} onChange={e=>update(setSeller,"gstin",e.target.value.toUpperCase())}/><Field label="Email" type="email" value={seller.email} onChange={e=>update(setSeller,"email",e.target.value)}/><Field label="Phone" value={seller.phone} onChange={e=>update(setSeller,"phone",e.target.value)}/><label className="invoice-field wide"><span>Address</span><textarea rows="3" value={seller.address} onChange={e=>update(setSeller,"address",e.target.value)}/></label></div></Section>
 <Section number="2" title="Customer Details"><div className="invoice-grid two"><Field label="Customer Name" required value={buyer.name} onChange={e=>update(setBuyer,"name",e.target.value)}/><Field label="GSTIN" value={buyer.gstin} onChange={e=>update(setBuyer,"gstin",e.target.value.toUpperCase())}/><Field label="Email" type="email" value={buyer.email} onChange={e=>update(setBuyer,"email",e.target.value)}/><Field label="Phone" value={buyer.phone} onChange={e=>update(setBuyer,"phone",e.target.value)}/><label className="invoice-field wide"><span>Address</span><textarea rows="3" value={buyer.address} onChange={e=>update(setBuyer,"address",e.target.value)}/></label></div></Section>
 <Section number="3" title="Receipt Details"><div className="invoice-grid three"><Field label="Receipt Number" required value={receipt.number} onChange={e=>update(setReceipt,"number",e.target.value)}/><Field label="Receipt Date" required type="date" value={receipt.date} onChange={e=>update(setReceipt,"date",e.target.value)}/><label className="invoice-field"><span>Payment Method</span><select value={receipt.method} onChange={e=>update(setReceipt,"method",e.target.value)}><option>UPI</option><option>Cash</option><option>Bank Transfer</option><option>Credit Card</option><option>Debit Card</option><option>Cheque</option><option>Other</option></select></label><Field label="Payment Reference" placeholder="Transaction / cheque no." value={receipt.reference} onChange={e=>update(setReceipt,"reference",e.target.value)}/><Field label="GST Rate (%)" type="number" min="0" max="100" step="0.01" value={receipt.gstRate} onChange={e=>update(setReceipt,"gstRate",e.target.value)}/><Field label="Discount (₹)" type="number" min="0" step="0.01" value={receipt.discount} onChange={e=>update(setReceipt,"discount",e.target.value)}/><label className="invoice-field wide"><span>Notes</span><textarea rows="2" value={receipt.notes} onChange={e=>update(setReceipt,"notes",e.target.value)}/></label></div></Section>
 <Section number="4" title="Items / Services"><div className="invoice-item-editor"><div className="invoice-item-head receipt-item-head"><span>#</span><span>Description</span><span>Qty</span><span>Rate (₹)</span><span>Amount (₹)</span><span>Action</span></div>{items.map((x,i)=><div className="invoice-item-row receipt-item-row" key={x.id}><span>{i+1}</span><input placeholder="Item / Service" value={x.description} onChange={e=>setItems(l=>l.map(v=>v.id===x.id?{...v,description:e.target.value}:v))}/><input type="number" min="0" step="1" value={x.quantity} onChange={e=>setItems(l=>l.map(v=>v.id===x.id?{...v,quantity:e.target.value}:v))}/><input type="number" min="0" step="0.01" value={x.rate} onChange={e=>setItems(l=>l.map(v=>v.id===x.id?{...v,rate:e.target.value}:v))}/><strong>{money((Number(x.quantity)||0)*(Number(x.rate)||0))}</strong><button type="button" className="invoice-remove" disabled={items.length===1} onClick={()=>setItems(l=>l.filter(v=>v.id!==x.id))}>Remove</button></div>)}</div><button type="button" className="invoice-add-item" onClick={()=>setItems(l=>[...l,makeItem()])}>+ Add Item</button></Section>
 {error&&<div className="invoice-error">{error}</div>}<button className="invoice-save" disabled={saving} onClick={save}>{saving?"Saving…":"Save Receipt"}</button>{history.length>0&&<div className="tool-history"><h3>Saved receipts</h3>{history.slice(0,10).map(d=><div key={d.id} className="document-row"><span>{d.document_number}</span><a href={getToolPdfUrl(d.id,visitorId)}>PDF</a></div>)}</div>}
 </div><aside className="invoice-preview-panel"><div className="invoice-preview-label">LIVE PREVIEW</div><Preview seller={seller} buyer={buyer} receipt={receipt} items={items} totals={totals}/></aside></div></div></main>;
}
