import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getAttribution, getToolVisitorId, trackToolEvent } from "../services/api";
import GstInvoiceTool from "./GstInvoiceTool";
import QuotationTool from "./QuotationTool";
import ReceiptTool from "./ReceiptTool";
import GstCalculatorTool from "./GstCalculatorTool";
import QrGeneratorTool from "./QrGeneratorTool";
import "../styles/free-tools.css";

const money = (n) => `₹${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
function Field({ label, ...props }) { return <label className="tool-field"><span>{label}</span><input {...props} /></label>; }
function Shell({ title, description, children }) { return <main className="tool-page"><div className="tool-container"><Link className="tool-back" to="/tools">← All Free Tools</Link><div className="tool-heading"><span className="eyebrow-cyan">FREE TOOL</span><h1>{title}</h1><p>{description}</p></div><div className="tool-workspace">{children}</div></div></main>; }
function useToolEvent(slug) { useEffect(() => { const visitorId=getToolVisitorId(), a=getAttribution(); localStorage.setItem("fw_last_tool_slug", slug); trackToolEvent({ tool: slug, event_type: "tool_open", visitor_id: visitorId, session_id: visitorId, ...a }).catch(() => {}); }, [slug]); }
function UTMBuilder() { const [f,setF]=useState({url:"https://example.com",source:"instagram",medium:"social",campaign:"summer_sale",term:"",content:""}); const set=(k,v)=>setF(x=>({...x,[k]:v})); const result=useMemo(()=>{try{const u=new URL(f.url);[["utm_source",f.source],["utm_medium",f.medium],["utm_campaign",f.campaign],["utm_term",f.term],["utm_content",f.content]].forEach(([k,v])=>v&&u.searchParams.set(k,v));return u.toString();}catch{return "Enter a valid URL";}},[f]); return <Shell title="UTM Campaign Builder" description="Create clean campaign URLs for analytics without manually building query strings."><div className="tool-panel"><div className="tool-form-grid"><Field label="Website URL" value={f.url} onChange={e=>set("url",e.target.value)}/><Field label="Campaign Source" value={f.source} onChange={e=>set("source",e.target.value)}/><Field label="Campaign Medium" value={f.medium} onChange={e=>set("medium",e.target.value)}/><Field label="Campaign Name" value={f.campaign} onChange={e=>set("campaign",e.target.value)}/><Field label="Campaign Term (optional)" value={f.term} onChange={e=>set("term",e.target.value)}/><Field label="Campaign Content (optional)" value={f.content} onChange={e=>set("content",e.target.value)}/></div><div className="tool-output"><small>Generated URL</small><code>{result}</code><button className="button button-primary" onClick={()=>navigator.clipboard?.writeText(result)}>Copy URL</button></div></div></Shell>; }
function WhatsAppTool(){ const [phone,setPhone]=useState(""),[message,setMessage]=useState("Hi, I would like to know more about your services."),[qr,setQr]=useState(""); const normalized=phone.replace(/\D/g,""); const link=normalized?`https://wa.me/${normalized}?text=${encodeURIComponent(message)}`:""; const generate=async()=>{if(link)setQr(await (await import("qrcode")).default.toDataURL(link,{width:420,margin:2,errorCorrectionLevel:"H"}));}; return <Shell title="WhatsApp Link & QR Generator" description="Create a click-to-chat WhatsApp link and QR code for your business, website or campaign."><div className="tool-panel"><div className="tool-form-grid"><Field label="WhatsApp number (country code included)" placeholder="919876543210" value={phone} onChange={e=>setPhone(e.target.value)}/><label className="tool-field tool-field-wide"><span>Pre-filled message</span><textarea rows="4" value={message} onChange={e=>setMessage(e.target.value)}/></label></div><div className="tool-actions"><button className="button button-primary" onClick={generate}>Generate QR</button>{link&&<><button className="button button-secondary" onClick={()=>navigator.clipboard?.writeText(link)}>Copy WhatsApp Link</button><a className="button button-secondary" href={link} target="_blank" rel="noreferrer">Open WhatsApp</a></>}</div>{qr&&<div className="qr-result"><img src={qr} alt="WhatsApp QR code"/><a className="button button-secondary" href={qr} download="whatsapp-qr.png">Download PNG</a></div>}</div></Shell>; }
function PaymentReminder(){const [name,setName]=useState("Customer"),[amount,setAmount]=useState("5000"),[date,setDate]=useState(""),[tone,setTone]=useState("polite");const message=tone==="firm"?`Hello ${name}, this is a reminder that the payment of ${money(amount)} is outstanding${date?` and was due on ${date}`:""}. Please arrange the payment at your earliest convenience. Thank you.`:`Hello ${name}, just a gentle reminder regarding the outstanding payment of ${money(amount)}${date?`, due on ${date}`:""}. Please let us know if you need any details. Thank you!`;return <Shell title="Payment Reminder Generator" description="Create professional payment reminders ready to copy or share on WhatsApp."><div className="tool-panel"><div className="tool-form-grid"><Field label="Customer name" value={name} onChange={e=>setName(e.target.value)}/><Field label="Amount (₹)" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><Field label="Due date (optional)" type="date" value={date} onChange={e=>setDate(e.target.value)}/><label className="tool-field"><span>Tone</span><select value={tone} onChange={e=>setTone(e.target.value)}><option value="polite">Polite</option><option value="firm">Firm</option></select></label></div><div className="message-preview">{message}</div><button className="button button-primary" onClick={()=>navigator.clipboard?.writeText(message)}>Copy Message</button></div></Shell>;}
export default function ToolPage(){const {slug}=useParams();useToolEvent(slug);useEffect(()=>window.scrollTo({top:0,behavior:"smooth"}),[slug]);if(slug==="gst-invoice-generator")return <GstInvoiceTool/>;if(slug==="quotation-generator")return <QuotationTool/>;if(slug==="receipt-generator")return <ReceiptTool/>;if(slug==="gst-calculator")return <GstCalculatorTool/>;if(slug==="qr-generator")return <QrGeneratorTool/>;if(slug==="whatsapp-link-generator")return <WhatsAppTool/>;if(slug==="payment-reminder-generator")return <PaymentReminder/>;if(slug==="utm-builder")return <UTMBuilder/>;return <Shell title="Free Tool" description="Choose one of our available free tools."><div className="tool-panel"><Link className="button button-primary" to="/tools">Browse Free Tools</Link></div></Shell>;}
