import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import QRCode from "qrcode";
import { TOOLS } from "./ToolsPage";
import "../styles/free-tools.css";

const money = (n) => `₹${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
function Field({ label, ...props }) { return <label className="tool-field"><span>{label}</span><input {...props} /></label>; }
function Shell({ title, description, children }) { return <main className="tool-page"><div className="tool-container"><Link className="tool-back" to="/tools">← All Free Tools</Link><div className="tool-heading"><span className="eyebrow-cyan">FREE TOOL</span><h1>{title}</h1><p>{description}</p></div><div className="tool-workspace">{children}</div></div></main>; }

function GstCalculator() {
  const [amount,setAmount]=useState("10000"),[rate,setRate]=useState("18"),[mode,setMode]=useState("add"),[type,setType]=useState("intra");
  const a=Number(amount)||0,r=Number(rate)||0,tax=mode==="add"?a*r/100:a-a/(1+r/100),base=mode==="add"?a:a-tax,total=mode==="add"?a+tax:a;
  return <Shell title="GST Calculator" description="Add or remove GST instantly with a clear tax breakdown."><div className="tool-panel"><div className="tool-form-grid"><Field label="Amount (₹)" type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/><Field label="GST Rate (%)" type="number" min="0" value={rate} onChange={e=>setRate(e.target.value)}/><label className="tool-field"><span>Calculation</span><select value={mode} onChange={e=>setMode(e.target.value)}><option value="add">Add GST</option><option value="remove">Remove GST</option></select></label><label className="tool-field"><span>Tax Type</span><select value={type} onChange={e=>setType(e.target.value)}><option value="intra">CGST + SGST</option><option value="inter">IGST</option></select></label></div><div className="result-card"><div><small>Taxable amount</small><strong>{money(base)}</strong></div>{type==="intra"?<><div><small>CGST</small><strong>{money(tax/2)}</strong></div><div><small>SGST</small><strong>{money(tax/2)}</strong></div></>:<div><small>IGST</small><strong>{money(tax)}</strong></div>}<div><small>Total</small><strong>{money(total)}</strong></div></div></div></Shell>;
}

function UTMBuilder() {
  const [f,setF]=useState({url:"https://example.com",source:"instagram",medium:"social",campaign:"summer_sale",term:"",content:""}); const set=(k,v)=>setF(x=>({...x,[k]:v}));
  const result=useMemo(()=>{try{const u=new URL(f.url);[["utm_source",f.source],["utm_medium",f.medium],["utm_campaign",f.campaign],["utm_term",f.term],["utm_content",f.content]].forEach(([k,v])=>v&&u.searchParams.set(k,v));return u.toString();}catch{return "Enter a valid URL";}},[f]);
  return <Shell title="UTM Campaign Builder" description="Create clean campaign URLs for analytics without manually building query strings."><div className="tool-panel"><div className="tool-form-grid"><Field label="Website URL" value={f.url} onChange={e=>set("url",e.target.value)}/><Field label="Campaign Source" value={f.source} onChange={e=>set("source",e.target.value)}/><Field label="Campaign Medium" value={f.medium} onChange={e=>set("medium",e.target.value)}/><Field label="Campaign Name" value={f.campaign} onChange={e=>set("campaign",e.target.value)}/><Field label="Campaign Term (optional)" value={f.term} onChange={e=>set("term",e.target.value)}/><Field label="Campaign Content (optional)" value={f.content} onChange={e=>set("content",e.target.value)}/></div><div className="tool-output"><small>Generated URL</small><code>{result}</code><button className="button button-primary" onClick={()=>navigator.clipboard?.writeText(result)}>Copy URL</button></div></div></Shell>;
}

function QrPreview({data,name="qr-code.png"}){return <div className="qr-result"><img src={data} alt="Generated QR code"/><a className="button button-secondary" href={data} download={name}>Download PNG</a></div>;}
function QRTool(){
  const [value,setValue]=useState("https://flayerwings.com"),[logo,setLogo]=useState(""),[qr,setQr]=useState(""),canvas=useRef(null);
  const generate=async()=>{if(!value.trim())return;await QRCode.toCanvas(canvas.current,value,{width:480,margin:3,errorCorrectionLevel:"H"});if(!logo){setQr(canvas.current.toDataURL("image/png"));return;}const ctx=canvas.current.getContext("2d"),img=new Image();img.onload=()=>{const s=canvas.current.width*.22,x=(canvas.current.width-s)/2;ctx.fillStyle="white";ctx.fillRect(x-12,x-12,s+24,s+24);ctx.drawImage(img,x,x,s,s);setQr(canvas.current.toDataURL("image/png"));};img.src=logo;};
  return <Shell title="QR Code Generator" description="Generate a clean QR code or add your logo for a branded, scannable result."><div className="tool-panel"><Field label="QR content (URL, text, contact, etc.)" value={value} onChange={e=>setValue(e.target.value)}/><label className="tool-field"><span>Optional logo</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file){const r=new FileReader();r.onload=()=>setLogo(r.result);r.readAsDataURL(file);}}}/></label><div className="tool-actions"><button className="button button-primary" onClick={generate}>Generate QR</button></div><canvas ref={canvas} className="qr-canvas" width="480" height="480"/>{qr&&<QrPreview data={qr} name={logo?"branded-qr.png":"qr-code.png"}/>}</div></Shell>;
}
function WhatsAppTool(){
  const [phone,setPhone]=useState(""),[message,setMessage]=useState("Hi, I would like to know more about your services."),[qr,setQr]=useState("");const normalized=phone.replace(/\D/g,"");const link=normalized?`https://wa.me/${normalized}?text=${encodeURIComponent(message)}`:"";
  const generate=async()=>{if(link)setQr(await QRCode.toDataURL(link,{width:420,margin:2,errorCorrectionLevel:"H"}));};
  return <Shell title="WhatsApp Link & QR Generator" description="Create a click-to-chat WhatsApp link and QR code for your business, website or campaign."><div className="tool-panel"><div className="tool-form-grid"><Field label="WhatsApp number (country code included)" placeholder="919876543210" value={phone} onChange={e=>setPhone(e.target.value)}/><label className="tool-field tool-field-wide"><span>Pre-filled message</span><textarea rows="4" value={message} onChange={e=>setMessage(e.target.value)}/></label></div><div className="tool-actions"><button className="button button-primary" onClick={generate}>Generate QR</button>{link&&<><button className="button button-secondary" onClick={()=>navigator.clipboard?.writeText(link)}>Copy WhatsApp Link</button><a className="button button-secondary" href={link} target="_blank" rel="noreferrer">Open WhatsApp</a></>}</div>{qr&&<QrPreview data={qr} name="whatsapp-qr.png"/>}</div></Shell>;
}
function DocumentTool({kind}){
  const [business,setBusiness]=useState("Your Business"),[customer,setCustomer]=useState("Customer Name"),[number,setNumber]=useState(kind==="invoice"?"INV-001":kind==="quotation"?"QUO-001":"REC-001"),[item,setItem]=useState("Service"),[amount,setAmount]=useState("1000"),[gst,setGst]=useState("18");const tax=Number(amount||0)*Number(gst||0)/100;const title=kind==="invoice"?"GST Invoice":kind==="quotation"?"Quotation / Estimate":"Payment Receipt";
  return <Shell title={`${title} Generator`} description={`Create a professional ${title.toLowerCase()} with automatic totals and print/save as PDF.`}><div className="tool-panel"><div className="tool-form-grid"><Field label="Business name" value={business} onChange={e=>setBusiness(e.target.value)}/><Field label="Customer name" value={customer} onChange={e=>setCustomer(e.target.value)}/><Field label={`${title} number`} value={number} onChange={e=>setNumber(e.target.value)}/><Field label="Item / Service" value={item} onChange={e=>setItem(e.target.value)}/><Field label="Amount (₹)" type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/><Field label="GST (%)" type="number" min="0" value={gst} onChange={e=>setGst(e.target.value)}/></div><div className="document-preview"><div className="document-head"><div><h2>{business}</h2><span>{title}</span></div><strong>{number}</strong></div><div className="document-meta"><span>Customer<br/><b>{customer}</b></span><span>Date<br/><b>{new Date().toLocaleDateString("en-IN")}</b></span></div><div className="document-row document-row-head"><span>Description</span><span>Amount</span></div><div className="document-row"><span>{item}</span><span>{money(amount)}</span></div><div className="document-total"><span>Taxable amount</span><b>{money(amount)}</b><span>GST ({gst}%)</span><b>{money(tax)}</b><span>Total</span><strong>{money(Number(amount||0)+tax)}</strong></div></div><button className="button button-primary" onClick={()=>window.print()}>Print / Save as PDF</button></div></Shell>;
}
function PaymentReminder(){const [name,setName]=useState("Customer"),[amount,setAmount]=useState("5000"),[date,setDate]=useState(""),[tone,setTone]=useState("polite");const message=tone==="firm"?`Hello ${name}, this is a reminder that the payment of ${money(amount)} is outstanding${date?` and was due on ${date}`:""}. Please arrange the payment at your earliest convenience. Thank you.`:`Hello ${name}, just a gentle reminder regarding the outstanding payment of ${money(amount)}${date?`, due on ${date}`:""}. Please let us know if you need any details. Thank you!`;return <Shell title="Payment Reminder Generator" description="Create professional payment reminders ready to copy or share on WhatsApp."><div className="tool-panel"><div className="tool-form-grid"><Field label="Customer name" value={name} onChange={e=>setName(e.target.value)}/><Field label="Amount (₹)" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><Field label="Due date (optional)" type="date" value={date} onChange={e=>setDate(e.target.value)}/><label className="tool-field"><span>Tone</span><select value={tone} onChange={e=>setTone(e.target.value)}><option value="polite">Polite</option><option value="firm">Firm</option></select></label></div><div className="message-preview">{message}</div><button className="button button-primary" onClick={()=>navigator.clipboard?.writeText(message)}>Copy Message</button></div></Shell>;}
export default function ToolPage(){const {slug}=useParams();useEffect(()=>window.scrollTo({top:0,behavior:"smooth"}),[slug]);if(slug==="gst-calculator")return <GstCalculator/>;if(slug==="qr-generator")return <QRTool/>;if(slug==="whatsapp-link-generator")return <WhatsAppTool/>;if(slug==="gst-invoice-generator")return <DocumentTool kind="invoice"/>;if(slug==="quotation-generator")return <DocumentTool kind="quotation"/>;if(slug==="receipt-generator")return <DocumentTool kind="receipt"/>;if(slug==="payment-reminder-generator")return <PaymentReminder/>;if(slug==="utm-builder")return <UTMBuilder/>;return <Shell title="Free Tool" description="Choose one of our available free tools."><div className="tool-panel"><Link className="button button-primary" to="/tools">Browse Free Tools</Link></div></Shell>;}
